{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "decant.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.aws.region | default "us-west-2" }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.serviceAccount.esoName }}
{{- end }}
