apiVersion: rules.alerting.grafana.app/v0alpha1
kind: RecordingRule
metadata:
  name: decant-scrape-present
  annotations:
    grafana.app/folder: decant
  labels:
    grafana.app/folder: decant
spec:
  title: decant:scrape_present
  metric: decant:scrape_present
  targetDatasourceUID: grafanacloud-prom
  trigger:
    interval: 1m
  expressions:
    query:
      datasourceUID: grafanacloud-prom
      queryType: prometheus
      source: true
      relativeTimeRange: {from: 16m0s, to: 0s}
      model:
        datasource: {type: prometheus, uid: grafanacloud-prom}
        expr: 'present_over_time(decant_last_success_timestamp_seconds[15m])'
        instant: true
        range: false
        intervalMs: 1000
        maxDataPoints: 43200
        refId: query
