// SPDX-License-Identifier: AGPL-3.0-only

package config_test

import (
	"os"
	"reflect"
	"testing"

	"github.com/rknightion/genai-otel-bridge/internal/config"
	"github.com/rknightion/genai-otel-bridge/internal/config/gen/helmgen"
	"github.com/rknightion/genai-otel-bridge/internal/source/langsmith"
	"github.com/rknightion/genai-otel-bridge/internal/source/portkey"
)

// TestECSConfigExampleUpToDate is the drift gate for the generated ECS config example — the analogue
// of TestHelmGeneratedConfigUpToDate (active block) + TestHelmGeneratedExamplesUpToDate (examples) for
// the DynamoDB-backed ECS target. The whole file (deploy/ecs/terraform/config.example.yaml) is
// GENERATED by `make generate` from config.Config (helm tags + Go doc-comments under helmgen.ECSProfile)
// PLUS the commented all-loops/both-vendor example block (each source's ExampleSource(), env-refs
// neutralized). This re-runs that render IN-MEMORY and byte-compares the committed file, so any
// schema/example change fails here until `make generate` is re-run and committed.
//
// It is an EXTERNAL test package (like helm_example_test.go) because it imports the source packages to
// build the examples — an internal `package config` test cannot without an import cycle. Keep the
// example list in sync with internal/config/gen/main.go (the generator's RenderECSConfigFile call).
func TestECSConfigExampleUpToDate(t *testing.T) {
	const ecsConfigPath = "../../deploy/ecs/terraform/config.example.yaml"
	want, err := helmgen.RenderECSConfigFile(reflect.TypeFor[config.Config](), "config.go", []helmgen.Example{
		{Value: portkey.ExampleSource(), SettingsComments: portkey.ExampleSettingsComments()},
		{Value: langsmith.ExampleSource(), SettingsComments: langsmith.ExampleSettingsComments()},
	})
	if err != nil {
		t.Fatalf("render ECS config file: %v", err)
	}
	got, err := os.ReadFile(ecsConfigPath)
	if err != nil {
		t.Fatalf("read %s: %v", ecsConfigPath, err)
	}
	if string(got) != string(want) {
		t.Errorf("%s is stale — run `make generate`\n\n--- committed ---\n%s\n--- generated ---\n%s",
			ecsConfigPath, got, want)
	}
}
