// SPDX-License-Identifier: AGPL-3.0-only

package config

import (
	"os"
	"reflect"
	"testing"

	"github.com/rknightion/genai-otel-bridge/internal/config/gen/helmgen"
)

// TestHelmGeneratedConfigUpToDate is the forcing function that keeps the Helm chart's default
// config in lockstep with the Go config schema. The `config:` block in deploy/helm/values.yaml is
// GENERATED from config.Config (its helm:"..." render tags + Go doc-comments) by `make generate`.
// This test re-runs the generator IN-MEMORY (the same helmgen render function the generator binary
// calls — no shelling out) and byte-compares its output against the committed values.yaml region.
//
// A new/changed config field (tag, default, env ref, doc-comment) changes the generated bytes and
// fails this test until `make generate` is re-run and the result committed. It runs in the
// mandatory `go test ./...` gate. This SUPERSEDES the old reflection-parity alignment test: a
// generated file cannot drift from its own generator, so there is nothing left to assert by hand.
func TestHelmGeneratedConfigUpToDate(t *testing.T) {
	const (
		configSrc  = "config.go"
		valuesPath = "../../deploy/helm/values.yaml"
	)
	want, err := helmgen.RenderConfigBlock(reflect.TypeFor[Config](), configSrc)
	if err != nil {
		t.Fatalf("render config block: %v", err)
	}
	values, err := os.ReadFile(valuesPath)
	if err != nil {
		t.Fatalf("read %s: %v", valuesPath, err)
	}
	got, err := helmgen.ExtractConfigBlock(values)
	if err != nil {
		t.Fatalf("extract config block from values.yaml: %v", err)
	}
	if string(got) != string(want) {
		t.Errorf("values.yaml config block is stale — run `make generate`\n\n--- committed ---\n%s\n--- generated ---\n%s",
			got, want)
	}
}
